### ISSUE TITLE
new try for test in local ubuntu 20

### ISSUE THREAD

**Issue by johnfelipe** [LNS98/deep-learning-medical-app#7]
sudo apt update
	 
	sudo apt install apt-transport-https ca-certificates curl software-properties-common
	 
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	 
	sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
	 
	sudo apt update
	sudo apt install docker-ce
	sudo systemctl status Docker
	sudo usermod -aG docker ${USER}
	 
	su - ${USER}
	 
	id -nG
	docker

	docker info
	git clone https://github.com/johnfelipe/deep-learning-medical-app
	cd deep-learning-medical-app/
	apt install docker-compose
	docker-compose up

and show me this

	root@eh68221471012:~/deep-learning-medical-app# docker-compose up
	Creating network "deep-learning-medical-app_CrohnsNetwork" with the default driver
	Building server
	Step 1/6 : FROM python:3.7
	3.7: Pulling from library/python
	0e29546d541c: Pull complete
	9b829c73b52b: Pull complete
	cb5b7ae36172: Pull complete
	6494e4811622: Pull complete
	6f9f74896dfa: Pull complete
	fcb6d5f7c986: Pull complete
	7a72d131c196: Pull complete
	c4221d178521: Pull complete
	71d5c5b5a91f: Pull complete
	Digest: sha256:d9abbc0737ff8d23a546859c85903f1b8235a1495a405d5a47cbc55747f27b20
	Status: Downloaded newer image for python:3.7
	 ---> ad37de9b03ef
	Step 2/6 : WORKDIR /code
	 ---> Running in 0630625b85fd
	Removing intermediate container 0630625b85fd
	 ---> 9cdcf7cafe17
	Step 3/6 : COPY requirements.txt requirements.txt
	 ---> 2ca9be861710
	Step 4/6 : RUN pip install --upgrade -r requirements.txt
	 ---> Running in 5259fa5b010c
	Collecting git+git://github.com/epigramai/tfserving-python-predict-client.git (from -r requirements.txt (line 1))
	  Cloning git://github.com/epigramai/tfserving-python-predict-client.git to /tmp/pip-req-build-qx1g_0p6
	  Running command git clone -q git://github.com/epigramai/tfserving-python-predict-client.git /tmp/pip-req-build-qx1g_0p6
	  fatal: remote error:
		The unauthenticated git protocol on port 9418 is no longer supported.
	  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
	WARNING: Discarding git+git://github.com/epigramai/tfserving-python-predict-client.git. Command errored out with exit status 128: git clone -q git://github.com/epigramai/tfserving-python-predict-client.git /tmp/pip-req-build-qx1g_0p6 Check the logs for full command output.
	ERROR: Command errored out with exit status 128: git clone -q git://github.com/epigramai/tfserving-python-predict-client.git /tmp/pip-req-build-qx1g_0p6 Check the logs for full command output.
	WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
	You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
	ERROR: Service 'server' failed to build: The command '/bin/sh -c pip install --upgrade -r requirements.txt' returned a non-zero code: 1

how solve that?

**Comment by LNS98** [comment]
Hey - sorry for the late reply. I think this is due to a [new change from github](https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported).  I've pushed a new commit [here](https://github.com/LNS98/deep-learning-medical-app/commits/master) that should have fixed that.

**Comment by LNS98** [comment]
I'll close but do re-open if it hasn't solved it
