### ISSUE TITLE
Importerror 

### ISSUE THREAD

**Issue by chandansusanth7** [LNS98/deep-learning-medical-app#9]
![Uploading 20220316_120844.jpg…]()

**Comment by chandansusanth7** [comment]
Server is not starting

**Comment by LNS98** [comment]
I believe this is related to [this issue](https://stackoverflow.com/questions/71189819/python-docker-importerror-cannot-import-name-json-from-itsdangerous). I've updated with this [commit](https://github.com/LNS98/deep-learning-medical-app/commits/master). Can you try it and let me know if it works.

**Comment by chandansusanth7** [comment]
![20220319_212148](https://user-images.githubusercontent.com/84890768/159128336-a238a2bd-98be-483c-85b9-c98831e9ee0b.jpg)
I believe it is showing this

**Comment by chandansusanth7** [comment]
Instead of https we should use http in the requirements.txt file

**Comment by chandansusanth7** [comment]
Then the issues got resolved

**Comment by chandansusanth7** [comment]
![Uploading 16477060400722499042001408202944.jpg…]()
These are some warnings after this

**Comment by LNS98** [comment]
why do you think that the warnings are related to the `https` in the back-end/requirements.txt. But either way the warnings are not related to the original issue correct? So is it okay if I close this issue and you can open new ones with the specific problems

**Comment by chandansusanth7** [comment]
👍🏻👍🏻👍🏻👍🏻

**Comment by chandansusanth7** [comment]
> why do you think that the warnings are related to the `https` in the back-end/requirements.txt. But either way the warnings are not related to the original issue correct? So is it okay if I close this issue and you can open new ones with the specific problems

👍🏻👍🏻👍🏻👍🏻
